"""Initial Models

Revision ID: 83510be2f621
Revises: 
Create Date: 2025-05-04 17:20:24.175092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83510be2f621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
